In [2]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3,5)

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
a.shape

(3, 5)

In [7]:
a.ndim

2

In [8]:
a.dtype.name

'int32'

In [9]:
a.itemsize

4

In [10]:
a.size

15

In [11]:
type(a)

numpy.ndarray

In [12]:
a = np.array([2,3,4])

In [13]:
a

array([2, 3, 4])

In [14]:
b = np.array([1.2,3.4,5.1])

Explicitly specifying the array data type

In [15]:
b = np.array([[1,2],[3,4]],dtype = complex)

In [16]:
b

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((2,3,4),dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [21]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [22]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [23]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [24]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [26]:
from numpy import pi
x = np.linspace(0,2*pi,100)

In [27]:
f = np.sin(x)

In [28]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [35]:
a = np.array([20,30,40,50])
b = np.arange(4)
c = a-b
print(c)
print(b**2)

[20 29 38 47]
[0 1 4 9]


In [36]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

In [37]:
A*B#elementwise product

array([[2, 0],
       [0, 4]])

In [38]:
A@B#matrix product

array([[5, 4],
       [3, 4]])

In [39]:
A.dot(B)#another matrix product

array([[5, 4],
       [3, 4]])

In [40]:
a = np.random.random((2,3))

In [41]:
a

array([[0.50304718, 0.61043143, 0.8667452 ],
       [0.75916674, 0.63602077, 0.4438583 ]])

In [42]:
a.sum()

3.819269610941763

In [43]:
a.min()

0.44385829654578823

In [44]:
a.max()

0.8667451979088675

In [45]:
b = np.arange(12).reshape(3,4)

In [46]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [48]:
b.min(axis =1)

array([0, 4, 8])

In [49]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [50]:
B = np.arange(3)

In [51]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [52]:
C = np.array([2.,-1.,4.])

In [53]:
np.add(B,C)

array([2., 0., 6.])

In [54]:
a = np.arange(10)**3

In [55]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [56]:
a[2]

8

In [57]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [58]:
a[:6:2] = -1000

In [59]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [60]:
a[::-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [62]:
def f(x,y):
    return 10*x+y

In [63]:
b = np.fromfunction(f,(5,4),dtype=int)

In [64]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [65]:
b[2,3]

23

In [67]:
b[0:5,1]#each ro in the second column of b

array([ 1, 11, 21, 31, 41])

In [68]:
b[1:3,:]#each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [69]:
b[-1]

array([40, 41, 42, 43])

In [70]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [71]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [72]:
a = np.floor(10*np.random.random((3,4)))

In [73]:
a

array([[1., 8., 7., 6.],
       [8., 8., 3., 0.],
       [4., 1., 6., 0.]])

In [74]:
a.ravel()

array([1., 8., 7., 6., 8., 8., 3., 0., 4., 1., 6., 0.])

In [75]:
a.reshape(6,2)

array([[1., 8.],
       [7., 6.],
       [8., 8.],
       [3., 0.],
       [4., 1.],
       [6., 0.]])

In [76]:
a.T

array([[1., 8., 4.],
       [8., 8., 1.],
       [7., 3., 6.],
       [6., 0., 0.]])

In [77]:
a.reshape(3,4)

array([[1., 8., 7., 6.],
       [8., 8., 3., 0.],
       [4., 1., 6., 0.]])

In [78]:
a.reshape(4,3)

array([[1., 8., 7.],
       [6., 8., 8.],
       [3., 0., 4.],
       [1., 6., 0.]])

In [79]:
a

array([[1., 8., 7., 6.],
       [8., 8., 3., 0.],
       [4., 1., 6., 0.]])

In [80]:
a.resize((2,6))

In [83]:
a

array([[1., 8., 7., 6., 8., 8.],
       [3., 0., 4., 1., 6., 0.]])

In [85]:
a=np.floor(10*np.random.random((2,2)))

In [86]:
a

array([[2., 2.],
       [6., 3.]])

In [87]:
b = np.floor(10*np.random.random((2,2)))

In [88]:
b

array([[0., 4.],
       [7., 5.]])

In [89]:
np.vstack((a,b))

array([[2., 2.],
       [6., 3.],
       [0., 4.],
       [7., 5.]])

In [90]:
np.hstack((a,b))

array([[2., 2., 0., 4.],
       [6., 3., 7., 5.]])

In [91]:
a  = np.array([[1.0,2.0],[3.0,4.0]])

In [92]:
print(a)

[[1. 2.]
 [3. 4.]]


In [93]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [94]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [95]:
u  = np.eye(2)#unit 2*2 matrix: "eye" represents "I"

In [97]:
u

array([[1., 0.],
       [0., 1.]])

In [98]:
j = np.array([[0.0,-1.0],[1.0,0.0]])

In [99]:
j@j

array([[-1.,  0.],
       [ 0., -1.]])

In [104]:
X = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
            [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
            [[21, 22, 23], [24, 25, 26], [27, 28, 29]]])

In [105]:
X[1]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [106]:
X[:,1]

array([[ 4,  5,  6],
       [14, 15, 16],
       [24, 25, 26]])

In [108]:
X[1,1]

array([14, 15, 16])

In [109]:
X[:,1,1]

array([ 5, 15, 25])

In [110]:
X[1,:,1]

array([12, 15, 18])

In [111]:
X[1,1,1]

15

In [112]:
X[1:2,1:2]

array([[[14, 15, 16]]])

In [113]:
dataset = np.array ( [ [ 2, 4, 6, 8, 3, 2, 5] ,[
[ 7, 5, 3, 1, 6, 8, 0]] ,[
[ 1, 3, 2, 1, 0, 0, 8] ] ])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [114]:
dataset = np.array([[2,4,6,8,3,2,5],[7,5,3,1,6,8,0],[1,3,2,1,0,0,8]])

In [115]:
np.max(dataset,axis=1)-np.min(dataset,axis=1)

array([6, 8, 8])

In [116]:
a = np.array([[15.0,20.0,22.0,75.0,40.0,35.0]])

In [117]:
a = a*.01

In [118]:
a

array([[0.15, 0.2 , 0.22, 0.75, 0.4 , 0.35]])

: 